services:
  - type: web
    name: grpc-user-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 3000
